/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Amendment {
  'date' : string,
  'description' : string,
  'version' : string,
}
export interface Policy {
  'id' : bigint,
  'title' : string,
  'amendments' : Array<Amendment>,
  'stakeholders' : Array<string>,
  'policyType' : string,
  'year' : bigint,
  'sourceUrl' : string,
  'vertical' : string,
  'level' : string,
  'keyProvisions' : Array<string>,
  'summary' : string,
  'state' : [] | [string],
  'industryImpact' : string,
}
export type SubscriptionTier = { 'premium' : null } |
  { 'lite' : null };
export interface UserProfile {
  'name' : string,
  'email' : string,
  'organization' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activateLite' : ActorMethod<[], undefined>,
  'activatePremium' : ActorMethod<[], undefined>,
  'addPolicy' : ActorMethod<[Policy], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deletePolicy' : ActorMethod<[bigint], undefined>,
  'getAllPolicies' : ActorMethod<[], Array<Policy>>,
  'getAllVerticals' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCentralPolicies' : ActorMethod<[], Array<Policy>>,
  'getMySubscriptionTier' : ActorMethod<[], SubscriptionTier>,
  'getPoliciesByLevel' : ActorMethod<[string], Array<Policy>>,
  'getPoliciesByVertical' : ActorMethod<[string], Array<Policy>>,
  'getPoliciesByYear' : ActorMethod<[bigint], Array<Policy>>,
  'getPoliciesForEfficiency' : ActorMethod<[], Array<Policy>>,
  'getPoliciesForRenewableEnergy' : ActorMethod<[], Array<Policy>>,
  'getPoliciesForYearRange' : ActorMethod<[bigint, bigint], Array<Policy>>,
  'getPoliciesImpactingIndustry' : ActorMethod<[], Array<Policy>>,
  'getPolicyById' : ActorMethod<[bigint], Policy>,
  'getStatePolicies' : ActorMethod<[], Array<Policy>>,
  'getSubscriptionTier' : ActorMethod<[Principal], SubscriptionTier>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchPoliciesByKeyword' : ActorMethod<[string], Array<Policy>>,
  'updatePolicy' : ActorMethod<[Policy], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];