/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Amendment = IDL.Record({
  'date' : IDL.Text,
  'description' : IDL.Text,
  'version' : IDL.Text,
});
export const Policy = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'amendments' : IDL.Vec(Amendment),
  'stakeholders' : IDL.Vec(IDL.Text),
  'policyType' : IDL.Text,
  'year' : IDL.Nat,
  'sourceUrl' : IDL.Text,
  'vertical' : IDL.Text,
  'level' : IDL.Text,
  'keyProvisions' : IDL.Vec(IDL.Text),
  'summary' : IDL.Text,
  'state' : IDL.Opt(IDL.Text),
  'industryImpact' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'organization' : IDL.Opt(IDL.Text),
});
export const SubscriptionTier = IDL.Variant({
  'premium' : IDL.Null,
  'lite' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activateLite' : IDL.Func([], [], []),
  'activatePremium' : IDL.Func([], [], []),
  'addPolicy' : IDL.Func([Policy], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deletePolicy' : IDL.Func([IDL.Nat], [], []),
  'getAllPolicies' : IDL.Func([], [IDL.Vec(Policy)], ['query']),
  'getAllVerticals' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCentralPolicies' : IDL.Func([], [IDL.Vec(Policy)], ['query']),
  'getMySubscriptionTier' : IDL.Func([], [SubscriptionTier], []),
  'getPoliciesByLevel' : IDL.Func([IDL.Text], [IDL.Vec(Policy)], ['query']),
  'getPoliciesByVertical' : IDL.Func([IDL.Text], [IDL.Vec(Policy)], ['query']),
  'getPoliciesByYear' : IDL.Func([IDL.Nat], [IDL.Vec(Policy)], ['query']),
  'getPoliciesForEfficiency' : IDL.Func([], [IDL.Vec(Policy)], ['query']),
  'getPoliciesForRenewableEnergy' : IDL.Func([], [IDL.Vec(Policy)], ['query']),
  'getPoliciesForYearRange' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Policy)],
      ['query'],
    ),
  'getPoliciesImpactingIndustry' : IDL.Func([], [IDL.Vec(Policy)], ['query']),
  'getPolicyById' : IDL.Func([IDL.Nat], [Policy], ['query']),
  'getStatePolicies' : IDL.Func([], [IDL.Vec(Policy)], ['query']),
  'getSubscriptionTier' : IDL.Func(
      [IDL.Principal],
      [SubscriptionTier],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchPoliciesByKeyword' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Policy)],
      ['query'],
    ),
  'updatePolicy' : IDL.Func([Policy], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Amendment = IDL.Record({
    'date' : IDL.Text,
    'description' : IDL.Text,
    'version' : IDL.Text,
  });
  const Policy = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'amendments' : IDL.Vec(Amendment),
    'stakeholders' : IDL.Vec(IDL.Text),
    'policyType' : IDL.Text,
    'year' : IDL.Nat,
    'sourceUrl' : IDL.Text,
    'vertical' : IDL.Text,
    'level' : IDL.Text,
    'keyProvisions' : IDL.Vec(IDL.Text),
    'summary' : IDL.Text,
    'state' : IDL.Opt(IDL.Text),
    'industryImpact' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'organization' : IDL.Opt(IDL.Text),
  });
  const SubscriptionTier = IDL.Variant({
    'premium' : IDL.Null,
    'lite' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activateLite' : IDL.Func([], [], []),
    'activatePremium' : IDL.Func([], [], []),
    'addPolicy' : IDL.Func([Policy], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deletePolicy' : IDL.Func([IDL.Nat], [], []),
    'getAllPolicies' : IDL.Func([], [IDL.Vec(Policy)], ['query']),
    'getAllVerticals' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCentralPolicies' : IDL.Func([], [IDL.Vec(Policy)], ['query']),
    'getMySubscriptionTier' : IDL.Func([], [SubscriptionTier], []),
    'getPoliciesByLevel' : IDL.Func([IDL.Text], [IDL.Vec(Policy)], ['query']),
    'getPoliciesByVertical' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Policy)],
        ['query'],
      ),
    'getPoliciesByYear' : IDL.Func([IDL.Nat], [IDL.Vec(Policy)], ['query']),
    'getPoliciesForEfficiency' : IDL.Func([], [IDL.Vec(Policy)], ['query']),
    'getPoliciesForRenewableEnergy' : IDL.Func(
        [],
        [IDL.Vec(Policy)],
        ['query'],
      ),
    'getPoliciesForYearRange' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Policy)],
        ['query'],
      ),
    'getPoliciesImpactingIndustry' : IDL.Func([], [IDL.Vec(Policy)], ['query']),
    'getPolicyById' : IDL.Func([IDL.Nat], [Policy], ['query']),
    'getStatePolicies' : IDL.Func([], [IDL.Vec(Policy)], ['query']),
    'getSubscriptionTier' : IDL.Func(
        [IDL.Principal],
        [SubscriptionTier],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchPoliciesByKeyword' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Policy)],
        ['query'],
      ),
    'updatePolicy' : IDL.Func([Policy], [], []),
  });
};

export const init = ({ IDL }) => { return []; };