/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Amendment {
    date: string;
    description: string;
    version: string;
}
export interface Policy {
    id: bigint;
    title: string;
    amendments: Array<Amendment>;
    stakeholders: Array<string>;
    policyType: string;
    year: bigint;
    sourceUrl: string;
    vertical: string;
    level: string;
    keyProvisions: Array<string>;
    summary: string;
    state?: string;
    industryImpact: string;
}
export interface UserProfile {
    name: string;
    email: string;
    organization?: string;
}
export enum SubscriptionTier {
    premium = "premium",
    lite = "lite"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    activateLite(): Promise<void>;
    activatePremium(): Promise<void>;
    addPolicy(policy: Policy): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deletePolicy(id: bigint): Promise<void>;
    getAllPolicies(): Promise<Array<Policy>>;
    getAllVerticals(): Promise<Array<string>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCentralPolicies(): Promise<Array<Policy>>;
    getMySubscriptionTier(): Promise<SubscriptionTier>;
    getPoliciesByLevel(level: string): Promise<Array<Policy>>;
    getPoliciesByVertical(vertical: string): Promise<Array<Policy>>;
    getPoliciesByYear(year: bigint): Promise<Array<Policy>>;
    getPoliciesForEfficiency(): Promise<Array<Policy>>;
    getPoliciesForRenewableEnergy(): Promise<Array<Policy>>;
    getPoliciesForYearRange(startYear: bigint, endYear: bigint): Promise<Array<Policy>>;
    getPoliciesImpactingIndustry(): Promise<Array<Policy>>;
    getPolicyById(id: bigint): Promise<Policy>;
    getStatePolicies(): Promise<Array<Policy>>;
    getSubscriptionTier(user: Principal): Promise<SubscriptionTier>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchPoliciesByKeyword(keyword: string): Promise<Array<Policy>>;
    updatePolicy(policy: Policy): Promise<void>;
}
import type { Amendment as _Amendment, Policy as _Policy, SubscriptionTier as _SubscriptionTier, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async activateLite(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.activateLite();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateLite();
            return result;
        }
    }
    async activatePremium(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.activatePremium();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activatePremium();
            return result;
        }
    }
    async addPolicy(arg0: Policy): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPolicy(to_candid_Policy_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPolicy(to_candid_Policy_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deletePolicy(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePolicy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePolicy(arg0);
            return result;
        }
    }
    async getAllPolicies(): Promise<Array<Policy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPolicies();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPolicies();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVerticals(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVerticals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVerticals();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCentralPolicies(): Promise<Array<Policy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCentralPolicies();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCentralPolicies();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySubscriptionTier(): Promise<SubscriptionTier> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySubscriptionTier();
                return from_candid_SubscriptionTier_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySubscriptionTier();
            return from_candid_SubscriptionTier_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPoliciesByLevel(arg0: string): Promise<Array<Policy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPoliciesByLevel(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPoliciesByLevel(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPoliciesByVertical(arg0: string): Promise<Array<Policy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPoliciesByVertical(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPoliciesByVertical(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPoliciesByYear(arg0: bigint): Promise<Array<Policy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPoliciesByYear(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPoliciesByYear(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPoliciesForEfficiency(): Promise<Array<Policy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPoliciesForEfficiency();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPoliciesForEfficiency();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPoliciesForRenewableEnergy(): Promise<Array<Policy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPoliciesForRenewableEnergy();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPoliciesForRenewableEnergy();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPoliciesForYearRange(arg0: bigint, arg1: bigint): Promise<Array<Policy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPoliciesForYearRange(arg0, arg1);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPoliciesForYearRange(arg0, arg1);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPoliciesImpactingIndustry(): Promise<Array<Policy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPoliciesImpactingIndustry();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPoliciesImpactingIndustry();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPolicyById(arg0: bigint): Promise<Policy> {
        if (this.processError) {
            try {
                const result = await this.actor.getPolicyById(arg0);
                return from_candid_Policy_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPolicyById(arg0);
            return from_candid_Policy_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStatePolicies(): Promise<Array<Policy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatePolicies();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatePolicies();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubscriptionTier(arg0: Principal): Promise<SubscriptionTier> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriptionTier(arg0);
                return from_candid_SubscriptionTier_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriptionTier(arg0);
            return from_candid_SubscriptionTier_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchPoliciesByKeyword(arg0: string): Promise<Array<Policy>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPoliciesByKeyword(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPoliciesByKeyword(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePolicy(arg0: Policy): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePolicy(to_candid_Policy_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePolicy(to_candid_Policy_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Policy_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Policy): Policy {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionTier_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionTier): SubscriptionTier {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    organization: [] | [string];
}): {
    name: string;
    email: string;
    organization?: string;
} {
    return {
        name: value.name,
        email: value.email,
        organization: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.organization))
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    amendments: Array<_Amendment>;
    stakeholders: Array<string>;
    policyType: string;
    year: bigint;
    sourceUrl: string;
    vertical: string;
    level: string;
    keyProvisions: Array<string>;
    summary: string;
    state: [] | [string];
    industryImpact: string;
}): {
    id: bigint;
    title: string;
    amendments: Array<Amendment>;
    stakeholders: Array<string>;
    policyType: string;
    year: bigint;
    sourceUrl: string;
    vertical: string;
    level: string;
    keyProvisions: Array<string>;
    summary: string;
    state?: string;
    industryImpact: string;
} {
    return {
        id: value.id,
        title: value.title,
        amendments: value.amendments,
        stakeholders: value.stakeholders,
        policyType: value.policyType,
        year: value.year,
        sourceUrl: value.sourceUrl,
        vertical: value.vertical,
        level: value.level,
        keyProvisions: value.keyProvisions,
        summary: value.summary,
        state: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.state)),
        industryImpact: value.industryImpact
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    premium: null;
} | {
    lite: null;
}): SubscriptionTier {
    return "premium" in value ? SubscriptionTier.premium : "lite" in value ? SubscriptionTier.lite : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Policy>): Array<Policy> {
    return value.map((x)=>from_candid_Policy_n6(_uploadFile, _downloadFile, x));
}
function to_candid_Policy_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Policy): _Policy {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    organization?: string;
}): {
    name: string;
    email: string;
    organization: [] | [string];
} {
    return {
        name: value.name,
        email: value.email,
        organization: value.organization ? candid_some(value.organization) : candid_none()
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    amendments: Array<Amendment>;
    stakeholders: Array<string>;
    policyType: string;
    year: bigint;
    sourceUrl: string;
    vertical: string;
    level: string;
    keyProvisions: Array<string>;
    summary: string;
    state?: string;
    industryImpact: string;
}): {
    id: bigint;
    title: string;
    amendments: Array<_Amendment>;
    stakeholders: Array<string>;
    policyType: string;
    year: bigint;
    sourceUrl: string;
    vertical: string;
    level: string;
    keyProvisions: Array<string>;
    summary: string;
    state: [] | [string];
    industryImpact: string;
} {
    return {
        id: value.id,
        title: value.title,
        amendments: value.amendments,
        stakeholders: value.stakeholders,
        policyType: value.policyType,
        year: value.year,
        sourceUrl: value.sourceUrl,
        vertical: value.vertical,
        level: value.level,
        keyProvisions: value.keyProvisions,
        summary: value.summary,
        state: value.state ? candid_some(value.state) : candid_none(),
        industryImpact: value.industryImpact
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
